### ISSUE TITLE
DSGVO-Konformität

### ISSUE THREAD

**Issue by ericfischereu** [leichtathletik/ladv-api#13]
Ich habe ein paar Stellen in der API gefunden, an denen ich bezweifle, dass die Umsetzung DSGVO konform ist.

Beispiel `ausDetail` -> Hier werden persönliche Daten (Name + E-Mail) derjenigen ausgegeben, die gemeldet haben. Einer Verwendung durch Dritte muss aber ausdrücklich zugestimmt werden, die Zustimmung muss auch dokumentiert sein.

Falls die Zustimmung nicht eingefordert werden kann, muss die API dringend angepasst werden.

**Comment by mschunk** [comment]
> Beispiel ausDetail -> Hier werden persönliche Daten (Name + E-Mail) derjenigen ausgegeben, die gemeldet haben.

Die Aussage ist falsch. `ausDetail` liefert keine Meldungen und keine Namen und Email von Meldern.

**Comment by ericfischereu** [comment]
> Die Aussage ist falsch. `ausDetail` liefert keine Meldungen und keine Namen und Email von Meldern.

Ok, da habe ich mich falsch ausgedrückt. Trotzdem stehen da E-Mail und Name des Veranstalters. Das ändert nichts an der Tatsache, dass hier personenbezogene Daten über eine API an Dritte weitergegeben werden.

Ich möchte nur darauf hinweisen, bevor jemand klagt. Solche Zugriffe benötigen inzwischen eine eindeutige Einwilligung. Wenn die eh schon vorhanden ist, bitte diesen Issue schließen. Falls nicht, sollten Sie sich darüber Gedanken machen, bevor das jemand sieht, der den Anwalt holt.

**Comment by mschunk** [comment]
Im Rahmen der DS-GVO Einführung haben wir mit einer zertifizierten Datenschutzbeauftragten alle Dienste von LADV überprüft. Nutzungsbedingungen, Datenschutzbestimmungen wurden entsprechend der neuen Gesetze angepasst. Auch gabe es mehrere Anpassungen in LADV selbst.
