### ISSUE TITLE
vereinList query=StG Baden-Baden/Gazelle nicht möglich

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/ladv-api#14]
Anfrage via Email:
`https://ladv.de/api/<apikey>/vereinList?query=StG%20Baden-Baden/Gazelle`

Antwort:
Parameter query ist ungültig: StG Baden-Baden/Gazelle

**Comment by mschunk** [comment]
Die Anfrage sollte funktionieren.

**Comment by FireEmerald** [comment]
Es geht speziell um die Zeichen `/` bzw `%2F` und `-`, welche aktuell nicht zulässig sind. Die API quittiert entsprechende Anfragen mit:
```
GET /api/<apikey>/vereinList?query=*baden%2F* HTTP/1.1

HTTP/1.1 403 Forbidden
Server: nginx
Date: Sun, 25 Aug 2019 10:38:17 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=REPLACED; Path=/; Secure; HttpOnly
X-Powered-By: PleskLin
MS-Author-Via: DAV

27
Parameter query ist ungültig: *baden/*
0

```

Außerdem scheint das Wildcard Zeichen `*` auf maximal 2 beschränkt zu sein. Somit ist auch kein Workaround ala `*baden*baden*` möglich.
```
GET /api/<apikey>/vereinList?query=*baden*baden* HTTP/1.1

HTTP/1.1 403 Forbidden
Server: nginx
Date: Sun, 25 Aug 2019 10:35:01 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=REPLACED; Path=/; Secure; HttpOnly
X-Powered-By: PleskLin
MS-Author-Via: DAV

2c
Parameter query ist ungültig: *baden*baden*
0

```

**Comment by mschunk** [comment]
GET `https://ladv.de/api/<apikey>/vereinList?query=StG%20Baden-Baden/Gazelle`
funktioniert nun

**Comment by mschunk** [comment]
> Außerdem scheint das Wildcard Zeichen * auf maximal 2 beschränkt zu sein. Somit ist auch kein Workaround ala `*baden*baden*` möglich.

Das Wildcard Zeichen kann nur am Anfang und/oder Ende des Suchstrings verwendet werden. Siehe die Beschreibung in der API Dokumentation:

> query: Pflichtfeld. Suchstring für den Vereinsnamen. Mindestens zwei Buchstaben.Der erste und letzte Buchstabe dürfen Wildcards (*) sein.
