### ISSUE TITLE
+ wird bei vereinList nicht unterstützt oder falsch interpretiert

### ISSUE THREAD

**Issue by FireEmerald** [leichtathletik/ladv-api#15]
**Gesuchter Verein:** [Teamwork-Sport + Events](https://ladv.de/verein/detail/10712/Teamwork-Sport--Events.htm)

```
GET /api/<apikey>/vereinList?query=*+%20* HTTP/1.1

HTTP/1.1 200 OK
Server: nginx
Date: Mon, 26 Aug 2019 09:49:25 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=<session>; Path=/; Secure; HttpOnly
X-Powered-By: PleskLin
MS-Author-Via: DAV

1e2
[{"name":"AMTV  Hamburg","vereinnumber":1101,"lv":"HH"},
{"name":"TV  Fischbek","vereinnumber":1150,"lv":"HH"},
{"name":"LAC  Mühl Rosin","vereinnumber":86,"lv":"MV"},
{"name":"FC  Voran Ohe","vereinnumber":1769,"lv":"SH"},
{"name":"TGS  Friesen Haspe","vereinnumber":1333,"lv":"WE"},
{"name":"SG EVO/STOAG Oberhausen  1960","vereinnumber":263,"lv":"NO"},
{"name":"TSV Bayer  04 Leverkusen","vereinnumber":769,"lv":"NO"},
{"name":"WSG  81 K. Wusterhausen","vereinnumber":61066,"lv":"BB"}]
0
```

Anstatt nach dem Zeichen `+` zu suchen, gibt die API Ergebnisse mit zwei Leerzeichen zurück. (Nebenbei bemerkt sollte es keinen Verein geben, welcher zwei Leerzeichen im Namen hat)

Folgende Anfragen geben nichts zurück:
```
GET /api/<apikey>/vereinList?query=*+%20E* HTTP/1.1
GET /api/<apikey>/vereinList?query=*t%20+%20E* HTTP/1.1
GET /api/<apikey>/vereinList?query=*Sport+Wanderv.Koblenz* HTTP/1.1

HTTP/1.1 200 OK
Server: nginx
Date: Mon, 26 Aug 2019 09:54:32 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=<session>; Path=/; Secure; HttpOnly
X-Powered-By: PleskLin
MS-Author-Via: DAV

2
[]
0
```

**Comment by mschunk** [comment]
> `GET /api/<apikey>/vereinList?query=*+%20* HTTP/1.1`

`+` ist ein `specal character` im URL encoding der Leerzeiche bedeutet. Die Anfrage ist damit gleichbedeutend wie `GET /api/<apikey>/vereinList?query=*  *` oder `GET /api/<apikey>/vereinList?query=*%20%20*`. Die Antwort ist m.E. korrekt.

> (Nebenbei bemerkt sollte es keinen Verein geben, welcher zwei Leerzeichen im Namen hat)

Die Daten werden so angeboten, wie wir sie von den Landesverbänden erhalten. Grundsätzlich würde ich zustimmen, dass zwei Leerzeichen ungewöhnlich sind.

> `GET https://ladv.de/api/<apikey>/vereinList?query=*Sport%2BWanderv.Koblenz*`

Anfragen wie diese funktionieren nun (korrektes URL encoding).
