### ISSUE TITLE
! wird bei vereinList nicht unterstützt

### ISSUE THREAD

**Issue by FireEmerald** [leichtathletik/ladv-api#18]
**Gesuchter Verein:** [Bonn läuft!](https://ladv.de/verein/detail/8409/Bonn-l%C3%A4uft%21.htm)

```
GET /api/<apikey>/vereinList?query=*läuft!* HTTP/1.1
GET /api/<apikey>/vereinList?query=*läuft%21* HTTP/1.1

HTTP/1.1 403 Forbidden
Server: nginx
Date: Mon, 26 Aug 2019 10:53:09 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=<session>; Path=/; Secure; HttpOnly
X-Powered-By: PleskLin
MS-Author-Via: DAV

28
Parameter query ist ungültig: *läuft!*
0
```

### Zusammenfassung:

Ich hab jetzt sämtliche Vereine in LADV einmal geprüft, welche auf https://ladv.de/verein zu finden sind.

**Vereine mit folgenden Zeichen sind vorhanden und werden gefunden:**
a-z A-Z 0-9 ß ä ö ü Ä Ö Ü ' " ( ) . - /
spaces kodiert mittels %20

**Vereine mit folgenden Zeichen sind vorhanden und werden nicht gefunden:**
& , ! +

**Comment by mschunk** [comment]
```
GET /api/<apikey>/vereinList?query=*läuft!*
GET /api/<apikey>/vereinList?query=*läuft%21*
```
funktioniert nun.

Danke für den Fehlerbereicht.
