### ISSUE TITLE
meldList - Keine Ergebnisse bei Gemeinschaften

### ISSUE THREAD

**Issue by stemeinke** [leichtathletik/ladv-api#19]
Hallo,

wenn ich eine Vereinsnummer einer Leichtathletikgemeinschaft an die API-Funktion meldList schicke, erhalte ich keine Ergebnisse. Bei den einzelnen Mitgliedsvereinen geht die Funktion. Es wäre schön, wenn die gleichen Ergebnisse auch bei der Gemeinschaftsnummer erscheinen würden. 
Es ist ja bereits möglich bei der Funktion veaList die Gemeinschaftsnummer zu verwenden.

**Comment by mschunk** [comment]
Das Problem sollte behoben sein. Wenn nicht, benötige ich die Abfrage (ohne API KEY) bei der Meldungen fehlen.

**Comment by stemeinke** [comment]
Vielen Dank das Problem ist behoben
