### ISSUE TITLE
Persönliche Bestleistung für Athleten

### ISSUE THREAD

**Issue by fxmohren** [leichtathletik/ladv-api#23]
Aktuell ist es leider nicht möglich die persönlichen Bestleistungen eines Athleten über einen einfachen API Aufruf zu erhalten.
Ein Umweg über `athletDetail` für alle Jahre ist notwendig um dann mit dem übergebenen Attribut `personalbest` die Bestleistung ausfindig zu machen.
Da die Persönliche Bestleistung somit eigentlich bekannt sein sollte, wäre es nützlich und Ressourcenschonend, wenn diese Beispielsweise unter einem neuen Punkt in `athletDetail` oder über eine neue Funktion aufrufbar wäre

**Comment by mschunk** [comment]
Sinnvoller Vorschlag - werden wir umsetzen.

Gäbe es auch interesse an den Jahresbestleistungen?

**Comment by fxmohren** [comment]
Super, vielen Dank!
Persönlich aktuell nicht, stört aber bestimmt auch nicht wenn es dabei ist.
Wobei diese ja auch schnell über eine Jahresleistungsabfrage und dem Attribut `yearbest` herauszufinden sind.
Also wir persönlich benötigen es aktuell nicht.

**Comment by fxmohren** [comment]
Aus organisatorischen Gründen: ab wann kann in etwa mit der Funktion gerechnet werden?

**Comment by plan4goal** [comment]
Hallo, gibt es eigentlich noch Bestrebungen die API zu erweitern? Kann man hier u.U. unterstützen?

**Comment by mschunk** [comment]
> Hallo, gibt es eigentlich noch Bestrebungen die API zu erweitern?

Ja.

Die Daten für alle Jahre wollen wir eigentlich nicht ausliefern, wenn nur die Bestleistungen gefragt sind. Was wir relativ einfach tun könnten, wäre gesteuert über einen Parameter nur die Bestleistungen auszuliefern. Also anstelle von `&year=...` würde man dann sagen `&best=true`

Wäre das eine gute Lösung für euch?

**Comment by plan4goal** [comment]
> Also anstelle von `&year=...` würde man dann sagen `&best=true`

Also für mich wäre das völlig in Ordnung, wobei man sicherlich auch die Kombination von `year `und `best `zulassen könnte. best alleine liefert die persönlichen Bestleistungen des Athleten und year + best die entsprechenden Saisonbestleistungen.

**Comment by fxmohren** [comment]
Für mich wäre das genau richtig.
Die Kombination aus year und best wie von @plan4goal erwähnt wäre natürlich eine schöne zusätzliche Funktion.

**Comment by mschunk** [comment]
Für athletDetail wird nun der Parameter `best=true` unterstützt. Dann werden alle Persönblichen Bestleistungen und Jahresbestleistungen ausgegeben.
