### ISSUE TITLE
Doppelte Werte veaList

### ISSUE THREAD

**Issue by stemeinke** [leichtathletik/ladv-api#24]
Hallo,

mir ist bei der API und eventuell auch auf dem LADV Webportal ein Fehler aufgefallen. 
Wenn ich den API Endpunkt veaList aufrufe, erhalte ich die gleiche Veranstaltung (gleiche ID) mehrfach als Antwort zurück. Das gleiche Phänomen hatte ich letztes Wochenende auch auf der LADV Seite selbst. Im Bearbeitungsmodus für Statistiker. Dort konnte ich das Problem heute aber nicht mehr erzeugen. 

Ich rufe die API wie folgt auf: 
https://ladv.de/api/"<apikey>"/veaList?lv=NI&vereinnumber=5401&datayear=2021&order=desc&limit=200

**Comment by mschunk** [comment]
An der API konnte das Problem nachvollziehen. Vielen Dank für den Hinweis darauf - wir kümmern uns darum.

> Im Bearbeitungsmodus für Statistiker. Dort konnte ich das Problem heute aber nicht mehr erzeugen.

Das wurde vor ein paar Tagen repariert.

**Comment by mschunk** [comment]
Das Problem wurde behoben. Danke für den Hinweis!

**Comment by stemeinke** [comment]
Vielen Dank
