### ISSUE TITLE
API liefert Leistungen mit alter AK

### ISSUE THREAD

**Issue by misteriks8** [leichtathletik/ladv-api#27]
Derzeit liefert die API Leistungen (z. B. über athletDetail) mit der alten Altersklasse (z.B. MJA oder SiB etc.). In der Leistungsdatenbank werden die Altersklassen jedoch "korrekt" angezeigt. 
Plant ihr die AKs umzustellen? Falls nicht werde ich mich wohl eine Mapping-Tabelle bauen!?

**Comment by mschunk** [comment]
Das sind die alten Altersklassencodes nach DLV DOS Austauschformat. Diese werden konsistent in der API verwendet. Ja, die API ist so alt, die neuen Altersklassencodes gab es damals noch nicht. Daran können wir auch nichts ändern, da wir eine bestehende API nie brechen.

Was wir tun können und nun auch tun, zusätzlich die aktuellen Altersklassencodes (`klasseNew`) und Disziplincodes (`disziplinNew`) ausliefern.

> Falls nicht werde ich mich wohl eine Mapping-Tabelle bauen!?

Dieses Mapping gibt es schon, siehe:
- [Altersklassen](https://ladv.de/entwickler/altersklassen)
- [Disziplinen](https://ladv.de/entwickler/disziplinen)

In der Spalte **Code** jeweils `klasseNew` bzw. `disziplinNew`; in der Spalte **Code*** jewils `klasse` bzw. `disziplin`.
