### ISSUE TITLE
World Ranking Competitions erkennen

### ISSUE THREAD

**Issue by lightsprint09** [leichtathletik/ladv-api#28]
Über die APIs ausList & ausDetail sollte erkennbar sein, ob ein Wettkampf als World Ranking Competitions ausgeschrieben wird.

**Comment by mschunk** [comment]
Für Veranstaltungen die als World Ranking Competition angemeldet sind wird nun `wrc true` in `ausList` und `ausDetail` mitgleiiefert. Die Daten sind ab 2021 vorhanden.

**Comment by lightsprint09** [comment]
Danke 👍🏾
